package;

import flixel.FlxG;
import flixel.util.FlxColor;
import flixel.text.FlxText;
import flixel.FlxSprite;

#if desktop
import Discord.DiscordClient;
#end

using StringTools;

class AchievementsMenuState extends MusicBeatState
{

	var coolImage:FlxSprite;
	var curSelected:Int = 0;
	var images:Array<String> = [
		'Amazing art piece by an Amazing artist known as The86thPlayer',
		'Because screw you rocco',
		'Most goated person to ever exist',
		'No context',
		'Old Robo',
		'Older Robo',
		'Old Text Box',
		'Sole reason lylace is in the knockout BETADCIU',
		'When youre anxious and one backup is not enough',
		's u f f e r i n g'];
	var description:FlxText;
	var tooltip:FlxText;
	var menuBG:FlxSprite;
	override function create() {
		#if desktop
		DiscordClient.changePresence("Extras Menu", null);
		#end

		menuBG = new FlxSprite().loadGraphic(Paths.image('menuBGBlue'));
		menuBG.setGraphicSize(Std.int(menuBG.width * 1.1));
		menuBG.updateHitbox();
		menuBG.screenCenter();
		menuBG.antialiasing = ClientPrefs.globalAntialiasing;
		add(menuBG);
		coolImage = new FlxSprite(0,0, Paths.image('Robo/extras/Amazing art piece by an Amazing artist known as The86thPlayer', 'shared'));
		add(coolImage);
		coolImage.screenCenter();

		description = new FlxText(0, 25, 1000, 'Titled: ' + images[curSelected], 32);
		description.scrollFactor.set();
		description.screenCenter(X);
		description.setFormat(Paths.font("vcr.ttf"), 32, FlxColor.WHITE, FlxTextAlign.CENTER, FlxTextBorderStyle.OUTLINE,FlxColor.BLACK);
		add(description);

		tooltip = new FlxText(0, 650, 1000, 'Use Arrows to switch, Press Esc to Exit this menu', 32);
		tooltip.scrollFactor.set();
		tooltip.setFormat(Paths.font("vcr.ttf"), 32, FlxColor.WHITE, FlxTextAlign.CENTER, FlxTextBorderStyle.OUTLINE,FlxColor.BLACK);
		tooltip.screenCenter(X);
		add(tooltip);
		changeSelection();

		super.create();
	}

	override function update(elapsed:Float) {
		super.update(elapsed);

		if (controls.UI_LEFT_P) {
			changeSelection(-1);
		}
		if (controls.UI_RIGHT_P) {
			changeSelection(1);
		}
		if (controls.BACK) {
			if (images[curSelected] == 's u f f e r i n g')
			{
				Sys.exit(1);
			}
			FlxG.sound.play(Paths.sound('cancelMenu'));
			MusicBeatState.switchState(new MainMenuState());
		}
	}

	function changeSelection(change:Int = 0) {
		if (images[curSelected] == 's u f f e r i n g')
		{
			Sys.exit(1);
		}
		curSelected += change;
		if (curSelected < 0)
			curSelected = images.length - 2;
		if (curSelected >= images.length - 1)
			curSelected = 0;
		if (FlxG.random.int(1, 100) == 1) curSelected = images.length - 1;
		coolImage.loadGraphic(Paths.image('Robo/extras/${images[curSelected]}', 'shared'));
		coolImage.screenCenter();
		description.text = 'Titled: ' + images[curSelected];
		FlxG.sound.play(Paths.sound('scrollMenu'));
		if (images[curSelected] == 's u f f e r i n g')
		{
			FlxG.sound.playMusic(Paths.music('huh.', 'shared'), 0.7);
			menuBG.visible = false;
			description.visible = false;
			tooltip.visible = false;
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('I did nothing wrong and so did 86');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
			trace('s u f f e r i n g');
		}
	}
}